const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                 "child":[
                     {
                         "buttons":[
                             "查看",
                             "新增",
                             "修改",
                             "删除"
                         ],
                         "menu":"教师管理",
                         "menuJump":"列表",
                         "tableName":"jiaoshi"
                     }
                 ],
                 "menu":"教师管理"
             }
			,{
				"child":[
					{
						"buttons":[
							"查看",
							"新增",
							"修改",
							"删除"
						],
						"menu":"用户管理",
						"menuJump":"列表",
						"tableName":"yonghu"
					}
				],
				"menu":"用户管理"
			}
			,{
				"child":[
					{
						"buttons":[
							"查看",
							"新增",
							"修改",
							"删除"
						],
						"menu":"实验室管理",
						"menuJump":"列表",
						"tableName":"shiyanshi"
					}
				],
				"menu":"实验室管理"
			}
			,{
				"child":[
					{
						"buttons":[
							"查看",
							"同意",
							"拒绝",
							"删除"
						],
						"menu":"实验室预约管理",
						"menuJump":"列表",
						"tableName":"yuye"
					}
				],
				"menu":"实验室预约管理"
			}
			,{
				"child":[
					{
						"buttons":[
							"查看",
							"删除"
						],
						"menu":"实验项目管理",
						"menuJump":"列表",
						"tableName":"shiyanxiangmu"
					}
				],
				"menu":"实验项目管理"
			}
			,{
				"child":[
					{
						"buttons":[
							"查看",
							"评分",
							"删除"
						],
						"menu":"学生实验管理",
						"menuJump":"列表",
						"tableName":"shiyan"
					}
				],
				"menu":"学生实验管理"
			}
             ,{
                 "child":[
                     {
                         "buttons":[
                             "查看",
                             "新增",
                             "修改",
                             "删除"
                         ],
                         "menu":"公告管理",
                         "menuJump":"列表",
                         "tableName":"news"
                     }
                 ],
                 "menu":"公告管理"
             }
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "预约"
                        ],
                        "menu":"实验室管理",
                        "menuJump":"列表",
                        "tableName":"shiyanshi"
                    }
                ],
                "menu":"实验室管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"实验室预约管理",
                        "menuJump":"列表",
                        "tableName":"yuye"
                    }
                ],
                "menu":"实验室预约管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "修改"
                        ],
                        "menu":"实验项目管理",
                        "menuJump":"列表",
                        "tableName":"shiyanxiangmu"
                    }
                ],
                "menu":"实验项目管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "评分"
                        ],
                        "menu":"学生实验管理",
                        "menuJump":"列表",
                        "tableName":"shiyan"
                    }
                ],
                "menu":"学生实验管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告管理"
            }
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"是",
        "hasFrontRegister":"是",
        "roleName":"教师",
        "tableName":"jiaoshi"
    },
    {
        "backMenu":[
           {
               "child":[
                   {
                       "buttons":[
                           "查看",
                           "进行实验"
                       ],
                       "menu":"实验项目管理",
                       "menuJump":"列表",
                       "tableName":"shiyanxiangmu"
                   }
               ],
               "menu":"实验项目管理"
           }
           ,{
               "child":[
                   {
                       "buttons":[
                           "查看",
                           "开始实验",
                           "结束实验"
                       ],
                       "menu":"学生实验管理",
                       "menuJump":"列表",
                       "tableName":"shiyan"
                   }
               ],
               "menu":"学生实验管理"
           }
           ,{
               "child":[
                   {
                       "buttons":[
                           "查看"
                       ],
                       "menu":"公告管理",
                       "menuJump":"列表",
                       "tableName":"news"
                   }
               ],
               "menu":"公告管理"
           }
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"是",
        "hasFrontRegister":"是",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]
	
	
	}
}
export default menu;
